
version: '3'
services:
  mysql-db3:
    container_name: mysql-db3
    image: mysql
    ports:
     - 330:3306
    environment:
      MYSQL_DATABASE: mydb
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
  springboot-CA:
#    container-name: spring-CA
    image: springboot-CA
    build:  .
    ports: 
      - 5000:5000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://sairam-aws.ckhocqd5s57m.ap-south-1.rds.amazonaws.com:3306/mydb
    depends_on:
      - mysql-db3 